# Generated by Django 4.1.5 on 2023-02-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_price'),
        ('equipment', '0001_initial'),
        ('providers', '0002_alter_provider_equipment_alter_provider_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='services',
        ),
        migrations.AddField(
            model_name='provider',
            name='equipment',
            field=models.ManyToManyField(null=True, to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='provider',
            name='services',
            field=models.ManyToManyField(null=True, to='services.service'),
        ),
    ]
