# Generated by Django 4.1.5 on 2023-02-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_price'),
        ('equipment', '0001_initial'),
        ('providers', '0003_remove_provider_equipment_remove_provider_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='equipment',
            field=models.ManyToManyField(related_name='providers', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='services',
            field=models.ManyToManyField(related_name='providers', to='services.service'),
        ),
    ]
