# Generated by Django 4.1.5 on 2023-02-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_price'),
        ('jobs', '0002_alter_job_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='area_type',
        ),
        migrations.AddField(
            model_name='job',
            name='services',
            field=models.ManyToManyField(related_name='jobs', to='services.service'),
        ),
        migrations.AddField(
            model_name='job',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
